language: cpp
sudo: required
dist: trusty

# Notes:
# $HOME -> /home/travis
# code checked out to (this is $PWD for the script) -> /home/travis/build/lanl/Draco
# travis will not install numdiff -> use ./.travis-install-dependencies.sh.

env:
  global:
#    - BLAS_blas_LIBRARY=/usr/lib/libblas.a
    - CC=gcc-7
    - CCACHE_CPP2=yes
    - CMAKE=$HOME/cmake-3.9.0-Linux-x86_64/bin/cmake
    - CTEST=$HOME/cmake-3.9.0-Linux-x86_64/bin/ctest
    - CXX=g++-7
    - FC=gfortran-7
#   - LAPACK_LIB_DIR=/usr/lib
    - OMP_NUM_THREADS=4
    - RANDOM123_INC_DIR=$HOME/Random123-1.09/include
    - VENDOR_DIR=${HOME}
    - topdir=/home/travis/build/KineticTheory/ci-demo
    - COVERAGE=ON
    - RANDOM123_VER=1.09
    - CMAKE_VERSION=3.9.0-Linux-x86_64
    - NUMDIFF_VER=5.8.1
    - CLANG_FORMAT_VER=6.0
    - DISTRO=trusty
    - OPENMPI_VER=1.10.5
    - GCCVER=7
  matrix:
    - STYLE=ON
    - WERROR=ON

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - gcc-7
      - g++-7
      - gfortran-7
      - environment-modules
      - graphviz
      - doxygen

before_install:
  - mkdir -p ${VENDOR_DIR}/bin & export PATH=${VENDOR_DIR}/bin:$PATH
  - pip install --upgrade --user pip
  - if [[ ${COVERAGE}  ]]; then pip install --user codecov; fi

install:
  - travis_wait 30 ./.travis-install-dependencies.sh

before_script:
  - if [[ ${WERROR} ]]; then for i in CC CXX Fortran; do eval export ${i}_FLAGS=\"-Werror\"; done; fi
  - if [[ ${COVERAGE} ]]; then for i in CC CXX Fortran; do eval export ${i}_FLAGS+=\" --coverage\"; done; fi

script:
  - printenv
  - ./.travis-run-tests.sh

after_success:
  - if [[ ${COVERAGE} ]]; then codecov --gcov-exec gcov-7; fi

cache:
  - ccache

compiler:
  - gcc-7

git:
  depth: 3


# output from printenv (2018-06-24)
