version: 1.0.{build}
# Don't build when repository is tagged.
skip_tags: true
max_jobs: 1
image: Visual Studio 2019
clone_depth: 3

environment:
  OMP_NUM_THREADS: 4
  RANDOM123_INC_DIR: c:\projects\vendors\Random123-1.08\include
  VENDOR_DIR: c:\projects\vendors
  PATH: c:\projects\vendors\bin;$(PATH)
  CMAKE_PREFIX_PATH: c:\projects\vendors\gsl-2.5;c:\projects\vendors\lapack-3.8.0;c:\projects\vendors\metis-5.1.0

# Notes: https://github.com/KineticTheory/Linux-HPC-Env/wiki/TPL-installs-via-vcpkg

build_script:
# we start at $(APPVEYOR_BUILD_FOLDER) = c:\projects\draco-2th1a
# can't put vendors in the source directory.
  - cd ..
  - curl -L -o win32-vendors.zip https://github.com/KineticTheory/ci-demo/releases/download/vendors-201809/win32-vendors.zip
  - 7z.exe -y x win32-vendors.zip
#  - curl -L -o cmake.zip https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-win64-x64.zip
#  - 7z.exe -y x cmake.zip
#  - set PATH=c:\projects\cmake-3.14.5-win64-x64\bin;%PATH%
  - mkdir build
  - cd build
  - set
  - vcpkg --triplet x64-windows install gsl
  - vcpkg list
# no MPI installed so force scalar builds.
  - cmake -G "Visual Studio 16 2019" -A x64 -DDRACO_C4=SCALAR %APPVEYOR_BUILD_FOLDER%
  - cmake --build . --config Debug
  - ctest -C Debug -j 2 --output-on-failure

#build:
#  verbosity: minimal


# Environment

# 7zip="C:\Program Files\7-Zip\7z.exe"
# ALLUSERSPROFILE=C:\ProgramData
# APPDATA=C:\Users\appveyor\AppData\Roaming
# APPVEYOR=True
# APPVEYOR_ACCOUNT_NAME=KineticTheory
# APPVEYOR_API_URL=http://localhost:1575/
# APPVEYOR_BUILD_AGENT_HYPERV_NIC_CONFIGURED=true
# APPVEYOR_BUILD_FOLDER=C:\projects\ci-demo
# APPVEYOR_BUILD_ID=30209974
# APPVEYOR_BUILD_NUMBER=79
# APPVEYOR_BUILD_VERSION=1.0.79
# APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2017
# APPVEYOR_JOB_ID=7lcx012a3xwnlpmu
# APPVEYOR_JOB_NUMBER=1
# APPVEYOR_PROJECT_ID=463591
# APPVEYOR_PROJECT_NAME=ci-demo
# APPVEYOR_PROJECT_SLUG=ci-demo
# APPVEYOR_REPO_BRANCH=new2020
# APPVEYOR_REPO_COMMIT=db88f76d5da7e97efc627c5ad792ca8213d32e5a
# APPVEYOR_REPO_COMMIT_AUTHOR=Kelly (KT) Thompson
# APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL=kgt@lanl.gov
# APPVEYOR_REPO_COMMIT_MESSAGE=Merge Draco's current ds++ directory.
# APPVEYOR_REPO_COMMIT_TIMESTAMP=2020-01-19T00:48:57.0000000Z
# APPVEYOR_REPO_NAME=KineticTheory/ci-demo
# APPVEYOR_REPO_PROVIDER=gitHub
# APPVEYOR_REPO_SCM=git
# APPVEYOR_REPO_TAG=false
# APPVEYOR_URL=https://ci.appveyor.com
# APR_ICONV_PATH=C:\Program Files (x86)\Subversion\iconv
# AVVM_DOWNLOAD_URL=https://appveyordownloads.blob.core.windows.net/avvm
# ChocolateyInstall=C:\ProgramData\chocolatey
# ChocolateyLastPathUpdate=132085876597000647
# CI=True
# CI_LINUX=False
# CI_WINDOWS=True
# CMAKE_PREFIX_PATH=c:\projects\vendors\gsl-2.5;c:\projects\vendors\lapack-3.8.0;c:\projects\vendors\metis-5.1.0
# CommonProgramFiles=C:\Program Files\Common Files
# CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
# CommonProgramW6432=C:\Program Files\Common Files
# COMPUTERNAME=APPVYR-WIN
# ComSpec=C:\Windows\system32\cmd.exe
# DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\
# EnableNuGetPackageRestore=true
# ERLANG_HOME=C:\Program Files\erl9.2
# GIT_LFS_PATH=C:\Program Files\Git LFS
# GOROOT=C:\go
# HOMEDRIVE=C:
# HOMEPATH=\Users\appveyor
# JAVA_HOME=C:\Progra~1\Java\jdk1.8.0
# lastexitcode=0
# LOCALAPPDATA=C:\Users\appveyor\AppData\Local
# LOGONSERVER=\\APPVYR-WIN
# M2_HOME=C:\Program Files (x86)\Apache\Maven
# MAVEN_HOME=C:\Program Files (x86)\Apache\Maven
# MSYS2_PATH_TYPE=inherit
# NUMBER_OF_PROCESSORS=2
# OMP_NUM_THREADS=4
# OPENSSL_CONF=C:\OpenSSL-Win32\bin\openssl.cfg
# OS=Windows_NT
# Path=c:\projects\vendors\bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\7-Zip;C:\Tools\GitVersion;C:\Tools\NuGet;C:\Program Files\Microsoft\Web Platform Installer\;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files\Mercurial\;C:\Program Files (x86)\Subversion\bin;C:\Tools\WebDriver;C:\Tools\Coverity\bin;C:\Tools\MSpec;C:\Tools\NUnit\bin;C:\Tools\NUnit3;C:\Tools\xUnit;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Ruby193\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Program Files (x86)\Apache\Maven\bin;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\CMake\bin;C:\Tools\curl\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130;C:\Program Files\dotnet\;C:\Tools\vcpkg;C:\Program Files (x86)\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\TestPlatform;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\erl9.2\bin;C:\Program Files (x86)\NSIS;C:\Tools\Octopus;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Docker\Docker\resources;C:\Program Files\LLVM\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\PowerShell\6\;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files\Meson\;C:\ProgramData\chocolatey\bin;C:\Program Files\Amazon\AWSCLI\;C:\Program Files (x86)\Yarn\bin\;C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps;C:\Users\appveyor\.dotnet\tools;C:\Users\appveyor\AppData\Roaming\npm;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Program Files\AppVeyor\BuildAgent\
# PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.CPL
# PROCESSOR_ARCHITECTURE=AMD64
# PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
# PROCESSOR_LEVEL=6
# PROCESSOR_REVISION=3f02
# ProgramData=C:\ProgramData
# ProgramFiles=C:\Program Files
# ProgramFiles(x86)=C:\Program Files (x86)
# ProgramW6432=C:\Program Files
# PROMPT=$P$G
# PSModulePath=C:\Users\appveyor\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Users\appveyor\Documents\WindowsPowerShell\Modules;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules;C:\Program Files (x86)\AWS Tools\PowerShell;C:\Program Files\AppVeyor\BuildAgent\Modules;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\
# PUBLIC=C:\Users\Public
# RANDOM123_INC_DIR=c:\projects\vendors\Random123-1.08\include
# SESSIONNAME=Console
# SystemDrive=C:
# SystemRoot=C:\Windows
# TEMP=C:\Users\appveyor\AppData\Local\Temp\1
# TMP=C:\Users\appveyor\AppData\Local\Temp\1
# USERDOMAIN=APPVYR-WIN
# USERDOMAIN_ROAMINGPROFILE=APPVYR-WIN
# USERNAME=appveyor
# USERPROFILE=C:\Users\appveyor
# VENDOR_DIR=c:\projects\vendors
# VS110COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
# VS120COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
# VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
# VSSDK140Install=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
# windir=C:\Windows
# WIX=C:\Program Files (x86)\WiX Toolset v3.11\
# xunit20=C:\Tools\xUnit20

